//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAdoni.KeyGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAdoni.KeyGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out the command line options..
        /// </summary>
        internal static string CommandLine_Options_Help_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?|h|help.
        /// </summary>
        internal static string CommandLine_Options_Help_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the key that will be used. Defaults to 2048..
        /// </summary>
        internal static string CommandLine_Options_KeySize_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeySize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s|keysize:.
        /// </summary>
        internal static string CommandLine_Options_KeySize_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeySize_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file paths of the file that will hold the {PUBLIC} and {PRIVATE} keys..
        /// </summary>
        internal static string CommandLine_Options_PrivatePath_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_PrivatePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i|private=.
        /// </summary>
        internal static string CommandLine_Options_PrivatePath_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_PrivatePath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file paths of the file that will hold the {PUBLIC} key..
        /// </summary>
        internal static string CommandLine_Options_PublicPath_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_PublicPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u|public=.
        /// </summary>
        internal static string CommandLine_Options_PublicPath_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_PublicPath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nAdoni Key file generator ({0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: nadoni.keygenerator.exe [OPTIONS].
        /// </summary>
        internal static string Help_Usage_Intro {
            get {
                return ResourceManager.GetString("Help_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input parameters were not valid..
        /// </summary>
        internal static string Output_Error_InvalidInput {
            get {
                return ResourceManager.GetString("Output_Error_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing one or more configuration values. Please see the help for more information..
        /// </summary>
        internal static string Output_Error_MissingValues {
            get {
                return ResourceManager.GetString("Output_Error_MissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key file written to: {0}..
        /// </summary>
        internal static string Output_Information_WrotePrivateKeyFile_WithFilePath {
            get {
                return ResourceManager.GetString("Output_Information_WrotePrivateKeyFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key file written to: {0}..
        /// </summary>
        internal static string Output_Information_WrotePublicKeyFile_WithFilePath {
            get {
                return ResourceManager.GetString("Output_Information_WrotePublicKeyFile_WithFilePath", resourceCulture);
            }
        }
    }
}
