//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAdoni.ManifestBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAdoni.ManifestBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL that points to the downloadable package..
        /// </summary>
        internal static string CommandLine_Options_DownloadUrl_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_DownloadUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u=|DownloadUrl=.
        /// </summary>
        internal static string CommandLine_Options_DownloadUrl_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_DownloadUrl_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the package file from which the manifest hash values will be computed..
        /// </summary>
        internal static string CommandLine_Options_FilePath_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f=|FilePath=.
        /// </summary>
        internal static string CommandLine_Options_FilePath_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_FilePath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out the command line options..
        /// </summary>
        internal static string CommandLine_Options_Help_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?|h|help.
        /// </summary>
        internal static string CommandLine_Options_Help_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the key container that contains the key that should be used to sign the manifest..
        /// </summary>
        internal static string CommandLine_Options_KeyContainer_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeyContainer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:|KeyContainerName:.
        /// </summary>
        internal static string CommandLine_Options_KeyContainer_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeyContainer_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the file that contains the key that should be used to sign the manifest..
        /// </summary>
        internal static string CommandLine_Options_KeyFile_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeyFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k:|KeyFile:.
        /// </summary>
        internal static string CommandLine_Options_KeyFile_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_KeyFile_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the location where the generated manifest file should be placed..
        /// </summary>
        internal static string CommandLine_Options_OutputPath_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_OutputPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o=|Output=.
        /// </summary>
        internal static string CommandLine_Options_OutputPath_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_OutputPath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the product..
        /// </summary>
        internal static string CommandLine_Options_ProductName_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_ProductName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n=|ProductName=.
        /// </summary>
        internal static string CommandLine_Options_ProductName_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_ProductName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the product..
        /// </summary>
        internal static string CommandLine_Options_Version_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_Version_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v=|ProductVersion=.
        /// </summary>
        internal static string CommandLine_Options_Version_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_Version_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nAdoni AutoUpdate manifest builder ({0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: nadoni.manifestbuilder.exe [OPTIONS].
        /// </summary>
        internal static string Help_Usage_Intro {
            get {
                return ResourceManager.GetString("Help_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the input parameters. Exception was: {0}.
        /// </summary>
        internal static string Log_Error_InvalidInputParameters_WithException {
            get {
                return ResourceManager.GetString("Log_Error_InvalidInputParameters_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclei.AutoUpdate.ManifestBuilder - Version: {0}.
        /// </summary>
        internal static string Log_Information_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Log_Information_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterApplicationName {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterApplicationVersion {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterDownloadUri {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterDownloadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input package file: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterFilePath {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key container name: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterKeyContainer {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterKeyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file path: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterKeyFile {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest output file: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterOutputPath {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing manifest.
        /// </summary>
        internal static string Log_Information_SigningManifest {
            get {
                return ResourceManager.GetString("Log_Information_SigningManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating manifest.
        /// </summary>
        internal static string Log_Information_WritingManifest {
            get {
                return ResourceManager.GetString("Log_Information_WritingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input parameters were not valid..
        /// </summary>
        internal static string Output_Error_InvalidInput {
            get {
                return ResourceManager.GetString("Output_Error_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing one or more configuration values. Please see the help for more information..
        /// </summary>
        internal static string Output_Error_MissingValues {
            get {
                return ResourceManager.GetString("Output_Error_MissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing manifest ....
        /// </summary>
        internal static string Output_Information_SigningManifest {
            get {
                return ResourceManager.GetString("Output_Information_SigningManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating manifest ....
        /// </summary>
        internal static string Output_Information_WritingManifest {
            get {
                return ResourceManager.GetString("Output_Information_WritingManifest", resourceCulture);
            }
        }
    }
}
